general:
  verbose: true

stages:
  Upload:
    enabled: true
  Deploy:
    enabled: false
  Integration Test:
    enabled: false

steps:
  integrationArtifactUpload:
    credentialsId: service-key
    filePath: package.zip
