general:
  productiveBranch: 'main'

steps:
  # Dummy step to validate that the secret is accessible
  # We won't deploy or upload any artifact here
  integrationArtifactGetMplStatus:
    host: 'https://uat-2fp4a4tq.it-cpitrial05-rt.cfapps.us10-001.hana.ondemand.com'
    credentialsId: 'service-key'
    integrationFlowId: 'filter_iflow'
