general:
  productiveBranch: 'main'

stages:
  Upload:
    enabled: true
  Deploy:
    enabled: true
  'Integration Test':
    enabled: false 

steps:
  integrationArtifactUpload:
    host: 'https://uat-2fp4a4tq.it-cpitrial05.cfapps.us10-001.hana.ondemand.com'
    credentialsId: 'service-key'
    integrationPackageId: 'filteriflow'       # your package ID
    integrationFlowId: 'filter_iflow'       # from MANIFEST.MF
    integrationFlowFilePath: 'filter_iflow.zip'

  integrationArtifactDeploy:
    host: 'https://uat-2fp4a4tq.it-cpitrial05.cfapps.us10-001.hana.ondemand.com'
    credentialsId: 'service-key'
    integrationFlowId: 'filter_iflow'
